apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-api
  namespace: egs-uniride
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-api
  template:
    metadata:
      labels:
        app: matching-api
    spec:
      containers:
      - name: matching-api
        image: registry.deti:5000/egs-uniride/matching-api
        ports:
          - containerPort: 8030
---
apiVersion: v1
kind: Service
metadata:
  name: matching-api
  namespace: egs-uniride
spec:
  ports:
    - protocol: TCP
      port: 8030
      name: matching-api-svc-port 
  selector:
    app: matching-api
  type: ClusterIP